#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

cd thermophysicalModels
./Allwmake
cd ..
wmake -j $targetType intermediate
wmake -j $targetType turbulence
wmake -j $targetType coalCombustion
wmake -j $targetType

#------------------------------------------------------------------------------
